return an error in an alert
the error is:
TypeError: props.results.map is not a function
I'll remove this for the final commit just so the site works.